In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Load Dataset into pandas Dataframe

In [3]:
crime_df=pd.read_csv(r'C:\Users\PC\crimeAnalysis\Dataset\districtwise-ipc-crimes-2017-onwards.csv')

In [4]:
crime_df.head(5)

,id,year,state_name,state_code,district_name,district_code,registration_circles,murder,clpbl_hmcrd_not_amt_murder,hit_and_run,...,ofnc_religion,cheating_impersonation,ofnc_mischief,arson,criminal_trespass,crlty_husbnd_relatives,crcl_false_fake_news_rumours,criminal_intimidation,insult_modesty_women,other_ipc_crimes
0,0,2017,Andhra Pradesh,28,Ananthapuramu,502,Anantapur,113.0,4.0,50.0,...,6.0,4.0,9.0,38.0,198.0,471.0,0.0,139.0,8.0,159.0
1,1,2017,Andhra Pradesh,28,Chittoor,503,Chittoor,70.0,5.0,36.0,...,0.0,0.0,4.0,7.0,100.0,212.0,1.0,26.0,12.0,470.0
2,2,2017,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,88.0,10.0,32.0,...,0.0,1.0,44.0,68.0,198.0,481.0,0.0,332.0,60.0,447.0
3,3,2017,Andhra Pradesh,28,East Godavari,505,East Godavari,69.0,14.0,138.0,...,12.0,0.0,25.0,40.0,848.0,601.0,0.0,50.0,127.0,48.0
4,4,2017,Andhra Pradesh,28,Ananthapuramu,502,Guntakal Railway,11.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,6.0